# Generated by Django 4.1 on 2024-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preview", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="H_Fields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("uci", "UCI"),
                            ("cardio", "Cardiologia"),
                            ("nefro", "Nefrologia"),
                            ("quiro", "Quirofano"),
                            ("radio", "Radiologia"),
                            ("gral", "General"),
                        ],
                        default="General",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("dni", models.CharField(blank=True, max_length=8)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("staff", "Personal"),
                            ("admin", "Gerencia"),
                            ("tech", "Ingenieria"),
                            ("med", "Medicina"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("area", models.ManyToManyField(blank=True, to="preview.h_fields")),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
