# Generated by Django 4.1 on 2024-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preview", "0003_h_fields_user_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="area",
        ),
        migrations.DeleteModel(
            name="H_Fields",
        ),
        migrations.AddField(
            model_name="user",
            name="area",
            field=models.TextField(blank=True),
        ),
    ]
