# Generated by Django 4.1 on 2024-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preview", "0004_remove_user_area_delete_h_fields_user_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
