# Generated by Django 4.1 on 2024-06-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preview", "0005_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="area",
            field=models.CharField(
                choices=[
                    ("uci", "UCI"),
                    ("cardio", "Cardiologia"),
                    ("nefro", "Nefrologia"),
                    ("quiro", "Quirofano"),
                    ("radio", "Radiologia"),
                    ("gral", "General"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
