# Generated by Django 4.1 on 2024-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preview", "0007_equipment_alter_user_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("op", "En operacion"),
                    ("cm", "Mantenimiento correctivo"),
                    ("pm", "Mantenimiento preventivo"),
                    ("os", "Fuera de servicio"),
                ],
                default="op",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=50)),
                ("date_admitted", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ir", "En reparacion"),
                            ("m", "En Mantenimiento"),
                            ("f", "Reparado"),
                            ("fm", "Mantenimiento finalizado"),
                            ("d", "Enviado a deposito"),
                        ],
                        default="op",
                        max_length=20,
                    ),
                ),
                ("commentary", models.CharField(max_length=500)),
                ("equipment", models.ManyToManyField(to="preview.equipment")),
                ("technician", models.ManyToManyField(to="preview.user")),
            ],
        ),
    ]
