# Generated by Django 4.1 on 2024-06-20 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preview", "0008_alter_equipment_status_reports"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reports",
            new_name="Report",
        ),
    ]
